### ISSUE TITLE
US02 BACKEND - como usuario quiero poder hacer log in

### ISSUE THREAD

**Issue by martincorestein** [4GeeksAcademy/proyecto-latam36-Agenda-de-eventos#4]
api route login
- acept
- - email
- - password (hashed)
- return
- - token

**Comment by Anajerar** [comment]
ruta: /api/login
method: POST
body (ejemplo):
{"email":"joe@4geeks.com",
"password":"123456789"}
response (ejemplo):
{
    "access token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczNDMyNTg0MSwianRpIjoiYWRhNTg5YjctM2JiMi00NTk1LThiYzgtZjI0NzkxY2FhZThlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImpvZUA0Z2Vla3MuY29tIiwibmJmIjoxNzM0MzI1ODQxLCJjc3JmIjoiMzg4MzI0NjAtY2E2OC00OTEzLWI1ZjYtOTJiYTFiZWQzYWIxIiwiZXhwIjoxNzM0MzI2NzQxfQ.G22xoatOvzIA9RgF2bWkDKpHWOh9CsC0DPXhI80nFFM"
}, 200
